apiVersion: v1
kind: Secret
metadata:
  name: harbor-dev-gpmn
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICAgIjEwLjYwLjE1Ni43MiI6IHsNCiAgICAgICAgICAgICJhdXRoIjogIlozQnRiaTFqYVRveE1qTTBOVFkzT0dGQVFRPT0iDQogICAgICAgIH0NCiAgICB9DQp9