apiVersion: v1
kind: Service
metadata:
  name: frontend-demo
  labels:
    app.kubernetes.io/part-of: daikin-payg
    app.kubernetes.io/name: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 9002
    protocol: TCP
  selector:
    app.kubernetes.io/part-of: daikin-payg
    app.kubernetes.io/name: frontend-primary
